export const overlay = [
  // 'absolute',
  // 'top-0',
  // 'bottom-0',
  // 'left-0',
  // 'right-0',
  // 'h-full',
  // 'w-full',
  'cursor-wait',
  'absolute',
  'inset-0',
  'bg-zinc-700/50',
  'transition',
  'duration-200',
  'ease-in',
  'flex',
  'justify-center',
  'place-items-center',
  'select-none',
  'overflow-clip',
]
